/* Generated By:JavaCC: Do not edit this line. JotaConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JotaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PUBLIC = 5;
  /** RegularExpression Id. */
  int CLASS = 6;
  /** RegularExpression Id. */
  int STATIC = 7;
  /** RegularExpression Id. */
  int VOID = 8;
  /** RegularExpression Id. */
  int MAIN = 9;
  /** RegularExpression Id. */
  int STRING = 10;
  /** RegularExpression Id. */
  int EXTENDS = 11;
  /** RegularExpression Id. */
  int OBRACKET = 12;
  /** RegularExpression Id. */
  int CBRACKET = 13;
  /** RegularExpression Id. */
  int OBRACES = 14;
  /** RegularExpression Id. */
  int CBRACES = 15;
  /** RegularExpression Id. */
  int OPARENTHESES = 16;
  /** RegularExpression Id. */
  int CPARENTHESES = 17;
  /** RegularExpression Id. */
  int RETURN = 18;
  /** RegularExpression Id. */
  int THIS = 19;
  /** RegularExpression Id. */
  int NEW = 20;
  /** RegularExpression Id. */
  int TRUE = 21;
  /** RegularExpression Id. */
  int FALSE = 22;
  /** RegularExpression Id. */
  int DENIAL = 23;
  /** RegularExpression Id. */
  int AND = 24;
  /** RegularExpression Id. */
  int IF = 25;
  /** RegularExpression Id. */
  int ELSE = 26;
  /** RegularExpression Id. */
  int WHILE = 27;
  /** RegularExpression Id. */
  int BOOLEAN = 28;
  /** RegularExpression Id. */
  int INT = 29;
  /** RegularExpression Id. */
  int SYSOUT = 30;
  /** RegularExpression Id. */
  int ASSIGNMENT = 31;
  /** RegularExpression Id. */
  int LESSTHAN = 32;
  /** RegularExpression Id. */
  int PLUS = 33;
  /** RegularExpression Id. */
  int MINUS = 34;
  /** RegularExpression Id. */
  int MULTIPLIED = 35;
  /** RegularExpression Id. */
  int SEMICOLON = 36;
  /** RegularExpression Id. */
  int COMMA = 37;
  /** RegularExpression Id. */
  int DOT = 38;
  /** RegularExpression Id. */
  int LENGTH = 39;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 40;
  /** RegularExpression Id. */
  int IDENTIFIER = 41;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"public\"",
    "\"class\"",
    "\"static\"",
    "\"void\"",
    "\"main\"",
    "\"String\"",
    "\"extends\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"return\"",
    "\"this\"",
    "\"new\"",
    "\"true\"",
    "\"false\"",
    "\"!\"",
    "\"&&\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"boolean\"",
    "\"int\"",
    "\"System.out.println\"",
    "\"=\"",
    "\"<\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"length\"",
    "<INTEGER_LITERAL>",
    "<IDENTIFIER>",
  };

}
